using System.Diagnostics;
using Ft8Sharp.Message;
using Xunit;
using Xunit.Abstractions;

namespace Ft8Sharp.Tests.Message;

/// <summary>
/// How large the collision problem actually is, measured rather than reasoned about.
/// </summary>
/// <remarks>
/// <para>
/// <b>This measures scale, not behaviour.</b> What the cache <em>does</em> on a collision is settled
/// beside the cache with constructed pairs; this says how often the case arises. It is here because
/// the answer is a thing the owner should eventually know and because the arithmetic is cheap: a
/// 12-bit hash has 4096 values, and there are rather more callsigns than that in the world.
/// </para>
/// <para>
/// <b>A number and its consequence, and nothing past that.</b> What Hamlet's display should do about
/// a refused callsign is the owner's under <c>CLAUDE.md</c> §12.1, so this reports a rate and stops.
/// </para>
/// <para>
/// <b>Every callsign here is this project's own datum</b>, generated by <see cref="CallsignCorpus"/>
/// from a stated seed. Nothing came out of the pinned clone, so the numbers may be reported.
/// </para>
/// </remarks>
public class Ft8CallsignHashCensusTests
{
    private readonly ITestOutputHelper _output;

    public Ft8CallsignHashCensusTests(ITestOutputHelper output) => _output = output;

    /// <summary>The seed the census corpus is generated from. Stated in the report.</summary>
    private const int Seed = 20861;

    /// <summary>How many distinct callsigns the census walks.</summary>
    private const int CorpusSize = 1_000_000;

    [Fact]
    public void TheCollisionCensusAcrossAMillionCallsigns()
    {
        var clock = Stopwatch.StartNew();
        var calls = CallsignCorpus.Distinct(Seed, CorpusSize);
        var generated = clock.ElapsedMilliseconds;

        var groups22 = new Dictionary<uint, int>();
        var groups12 = new Dictionary<uint, int>();
        var groups10 = new Dictionary<uint, int>();
        var hashable = 0;

        foreach (var call in calls)
        {
            if (!Ft8CallsignHash.TryCompute(call, out var h22, out var h12, out var h10))
            {
                continue;
            }

            hashable++;
            Count(groups22, h22);
            Count(groups12, h12);
            Count(groups10, h10);
        }

        clock.Stop();

        _output.WriteLine($"seed                          : {Seed}");
        _output.WriteLine(
            $"callsigns generated           : {calls.Count} distinct, across {CallsignCorpus.ShapeCount} shapes "
            + $"({CallsignCorpus.StandardShapeCount} of them standard basecall shapes)");
        _output.WriteLine($"of those, hashable            : {hashable}");
        _output.WriteLine($"generation time               : {generated} ms");
        _output.WriteLine($"census time including that    : {clock.ElapsedMilliseconds} ms");
        _output.WriteLine(string.Empty);
        _output.WriteLine($"{"width",-8}{"distinct calls",-16}{"distinct hashes",-18}{"colliding pairs",-18}largest group");

        Report("22-bit", groups22, hashable, Ft8CallsignHash.Bits22);
        Report("12-bit", groups12, hashable, Ft8CallsignHash.Bits12);
        Report("10-bit", groups10, hashable, Ft8CallsignHash.Bits10);

        Assert.Equal(CorpusSize, calls.Count);
        Assert.True(hashable > 0);

        // Every hash landed inside its width, which is the one thing here that could be wrong in a
        // way the counts would not show.
        Assert.True(groups22.Keys.All(k => k <= Ft8CallsignHash.Mask22));
        Assert.True(groups12.Keys.All(k => k < (1u << Ft8CallsignHash.Bits12)));
        Assert.True(groups10.Keys.All(k => k < (1u << Ft8CallsignHash.Bits10)));

        // The narrow widths cannot hold more values than the wide one does.
        Assert.True(groups12.Count <= groups22.Count);
        Assert.True(groups10.Count <= groups12.Count);

        void Report(string label, Dictionary<uint, int> groups, int total, int bits)
        {
            long pairs = 0;
            var largest = 0;
            foreach (var size in groups.Values)
            {
                pairs += (long)size * (size - 1) / 2;
                if (size > largest)
                {
                    largest = size;
                }
            }

            _output.WriteLine(
                $"{label,-8}{total,-16}{groups.Count,-18}{pairs,-18}{largest}"
                + $"   (the width holds {1L << bits} values)");
        }

        static void Count(Dictionary<uint, int> groups, uint hash) =>
            groups[hash] = groups.TryGetValue(hash, out var n) ? n + 1 : 1;
    }

    /// <summary>
    /// What the census means for an operator: how often a station this library has heard cannot be
    /// resolved from its hash because another station it has also heard shares that hash.
    /// </summary>
    /// <remarks>
    /// <b>Measured on a real cache rather than modelled.</b> A cache of the pin's own size is filled
    /// from the corpus and then asked for the 12-bit hash of every call it is holding — which is the
    /// most favourable question that can be asked of it, since every one of those calls is certainly
    /// present. The rate that comes back refused is the rate at which a station the receiver has
    /// genuinely heard will not resolve.
    /// </remarks>
    [Fact]
    public void WhatTheCensusMeansForAnOperator()
    {
        var calls = CallsignCorpus.Distinct(Seed, 4096);

        var cache = new Ft8CallsignCache();
        var held = new List<string>();
        foreach (var call in calls)
        {
            if (cache.Save(call) != Ft8CacheStore.Stored)
            {
                break;
            }

            held.Add(call);
        }

        var found = 0;
        var ambiguous = 0;
        foreach (var call in held)
        {
            Ft8CallsignHash.TryCompute(call, out _, out var h12, out _);
            switch (cache.TryLookup(Ft8CallsignHashWidth.Bits12, h12, out var resolved))
            {
                case Ft8CacheLookup.Found:
                    found++;
                    Assert.Equal(call, resolved);
                    break;
                case Ft8CacheLookup.Ambiguous:
                    ambiguous++;
                    Assert.Equal(string.Empty, resolved);
                    break;
                default:
                    Assert.Fail($"{call} is in the cache and its own hash did not find it.");
                    break;
            }
        }

        Assert.Equal(cache.Capacity, held.Count);
        Assert.Equal(held.Count, found + ambiguous);

        var rate = 100.0 * ambiguous / held.Count;
        _output.WriteLine($"seed                                  : {Seed}");
        _output.WriteLine($"callsigns held by a full cache        : {held.Count}");
        _output.WriteLine($"resolved from their own 12-bit hash   : {found}");
        _output.WriteLine($"refused because another call shares it: {ambiguous}");
        _output.WriteLine($"refusal rate at a full cache          : {rate:F1} per cent");
        _output.WriteLine(string.Empty);
        _output.WriteLine(
            "WHAT THAT MEANS: with a cache of this size full of stations, roughly this share of the "
            + "stations it has heard cannot be named from a 12-bit hash, because a second station it "
            + "has also heard shares that hash. Those decodes are refused rather than shown with one "
            + "of the two calls picked. What the display does about a refusal is not this library's "
            + "to decide.");

        Assert.True(rate >= 0 && rate <= 100);
    }
}
