@echo off
rem Unit 267's call into outcome-append.bat, written to a file because this
rem session's shell mangles or refuses long quoted argument lists.
call "%~dp0tools\arbiter\outcome-append.bat" ^
 267 ^
 B ^
 done ^
 "Measure the four criteria of step B against what the previous cut already shipped, then build only the proof missing - an out-of-privileges click driven through the application to a slot boundary, nothing keyed and the Send area saying so - and close the three on-screen criteria on a run tonight instead of on committed markup." ^
 "The instruction's expectation was right and the seam was genuinely empty: RefusedByLicence appeared nowhere in tests/Hamlet.App.Tests at all, and MainWindowViewModel.cs:8346's branch - the sentence an operator reads when the gate refuses his click - was asserted by nothing. What was NOT expected is the guard-off measurement. Switching RestrictTransmitToPrivileges off in Settings does not let the transmission through: Ft8TransmitSequence.Permits:443 accepts one of the gate's three ways of permitting and refuses an overridden permit outright, so the operator gets a different refusal rather than a transmission. Four of the five assertions were green whole on their first run; no product code was needed and none was written." ^
 continue ^
 "Step B had had no unit spent on it and the previous cut built the menu, the CQ button and the Send area without ever joining the licence gate to the operator's click. The gate was proved inside Ft8TransmitSequence.RunAsync on a sequence a test constructed, and the menu was proved to say so on a panel nobody clicked. Nothing drove his own click, with his own licence class and his own guard setting out of Settings, to a slot boundary." ^
 "Two on my own authority. First, the guard-off case is recorded as a measurement and left exactly as found, because work instruction 267 said to record it and not to decide it, and because changing it would mean editing the keying path's own gate. Second, the Send area line after a successful send was measured by adding a print and an addressee assertion to the test task 2 built, rather than by running an eighth committed test, because the seven named tests do not carry that string and the no-suite rule permits only those seven and what task 2 builds." ^
 "PHASE_PLAN.md step B's four exit criteria; its rule that a bench step's criteria are all satisfiable with no radio and none deferred to Tim; the ruling that nothing is forbidden in the menu and a repeat shows its count; and the third of the three things no unit may reason past - the Settings gate is not bypassable from any send path. Work instruction 267 task 3's named, bounded exception to the no-suite rule licensed the seven committed tests, each run alone by exact name." ^
 unknown ^
 "Tim can right-click a station he has decoded and send it a message with one click, with the one that conventionally comes next marked and nothing taken away from him, and he can call CQ from his own callsign and grid without typing. The Send area tells him what went out and to whom. And on a frequency his licence does not cover, Hamlet says so in the regulator's own words, cites the paragraph, names the message that did not go, and transmits nothing - proved from his click through the application to a slot boundary, with zero bytes at the port and the sound card never touched, rather than from a test that built its own transmitter." ^
 "" ^
 executed ^
 "All four must-pass criteria are met on evidence quotable from runs tonight, and none of them needed the radio. Criterion 1 by TheCqButtonSendsFromSettingsWithNoTypingAndNeverInventsAGrid, run alone: CQ KC3QIS FN00 with a grid set and CQ KC3QIS without, and no locator invented. Criterion 2 by four tests run alone, including EveryStationsPredictedMenuAppearsUnderTheMouse matching 5 of 5 stations' header strings on a real ContextRequested with every item enabled, and TheRepeatCountBelongsToTheClickAndNotToTheRow moving 73 to 73, 2nd time. Criterion 3 by OneClickIsOneMessageAcrossTwoBoundaries: first boundary Ran, second NothingArmed, 1 sink call, 2 port frames. Criterion 4 by the new TheLicenceGateHoldsFromTheClickTests, five assertions green: Technician on 14.074 through SendMessageCommand to AtSlotBoundaryAsync gives RefusedByLicence with Sent and Keyed both false, 0 sink calls and 0 bytes at the port; the same click as General sends, 1 sink call and 2 frames, so it is a gate and not a dead path; and the Send area reads - Hamlet did not send W1ABC KC3QIS -10: Technician privileges do not reach this frequency; it needs General. (97.301(e))"
exit /b %ERRORLEVEL%
