using System.Reflection;
using Hamlet.RadioEngine.Audio;
using Hamlet.RadioEngine.Cw;
using Xunit;
using Xunit.Abstractions;

namespace Hamlet.RadioEngine.Tests.Cw;

/// <summary>One recording made on the air, and what the radio was doing.</summary>
/// <param name="Name">The file, without its extension.</param>
/// <param name="Sidecar">Everything written beside it at the moment of capture.</param>
internal sealed record CapturedSignal(string Name, IReadOnlyDictionary<string, string> Sidecar)
{
    /// <summary>What the capture recorded for one field, or "".</summary>
    public string this[string field]
        => Sidecar.TryGetValue(field, out var value) ? value : "";
}

/// <summary>
/// The decoder against signals that were actually on the air (HM-DEC-091).
/// </summary>
/// <remarks>
/// <para>**THE SEVEN SYNTHETIC FIXTURES ALL PASSED WHILE THE DECODER WAS DEAF ON
/// THE AIR**, and that is the whole argument for these files. Morse generated by
/// the same understanding that built the decoder will confirm that understanding
/// for as long as anybody cares to run it. These two recordings are the first
/// evidence in the project capable of contradicting it.</para>
/// <para>Each carries the rig state at the moment of capture, so a failure here
/// can say what the radio was set to rather than only that something went wrong
/// (§0.0.1).</para>
/// <para>**WHAT THESE TESTS ASSERT IS DELIBERATELY NOT A TRANSCRIPT.** Nobody
/// knows what that station sent; there is no truth to compare against, and
/// inventing one would be worse than having none. What can be asserted is
/// everything that was measured independently and everything §0.0 forbids: the
/// tone is found, it is strong, and nothing is invented from the parts that
/// cannot be read.</para>
/// </remarks>
public sealed class CapturedSignalTests
{
    private readonly ITestOutputHelper _output;

    /// <summary>Creates the tests.</summary>
    /// <param name="output">Where the decode is printed.</param>
    public CapturedSignalTests(ITestOutputHelper output) => _output = output;

    /// <summary>Where the recordings live.</summary>
    public static string Folder { get; } = Path.Combine(
        RepositoryRoot(), "tests", "fixtures", "cw", "captured");

    /// <summary>Every recording, with its sidecar read.</summary>
    public static TheoryData<string> Names
    {
        get
        {
            var data = new TheoryData<string>();

            foreach (var wav in Directory.GetFiles(Folder, "*.wav").OrderBy(p => p))
            {
                data.Add(Path.GetFileNameWithoutExtension(wav));
            }

            return data;
        }
    }

    private static CapturedSignal Load(string name)
    {
        var fields = new Dictionary<string, string>(StringComparer.Ordinal);

        foreach (var line in File.ReadAllLines(Path.Combine(Folder, name + ".txt")))
        {
            var trimmed = line.Trim();
            var space = trimmed.IndexOf(' ');

            if (space > 0)
            {
                fields[trimmed[..space]] = trimmed[(space + 1)..].Trim();
            }
        }

        return new CapturedSignal(name, fields);
    }

    private static (CwDecoder Decoder, string Text) Decode(string name)
    {
        var audio = WavAudio.Read(Path.Combine(Folder, name + ".wav"));
        var decoder = new CwDecoder(audio.SampleRate, 600);
        var text = new System.Text.StringBuilder();

        decoder.CharacterDecoded += c => text.Append(c.Text);

        using var source = new BufferedAudioSource(audio);
        decoder.Listen(source);
        source.PumpAll();
        decoder.Flush();

        return (decoder, text.ToString().Trim());
    }

    /// <remarks>
    /// <para>Proves HM-DEC-091, and it is the assertion the brief asked for: **a
    /// decoder that cannot find the tone in these files fails the build.** Both
    /// were captured with a real station on frequency, and independent analysis
    /// put a strong keyed note in each.</para>
    /// <para>The pitch is checked against the sidecar's own reading rather than
    /// against a number typed here, so the fixture carries its own answer.</para>
    /// </remarks>
    [Theory]
    [MemberData(nameof(Names))]
    public void TheToneIsFound(string name)
    {
        var capture = Load(name);
        var (decoder, text) = Decode(name);
        var report = decoder.Report;

        _output.WriteLine($"{name}: {capture["Frequency"]} {capture["Mode"]} "
            + $"{capture["FilterBandwidth"]} pitch {capture["CwPitch"]} "
            + $"S-meter {capture["SMeter"]}");

        _output.WriteLine(
            $"  tone {report.ToneHz:0} Hz, snr {report.SnrDb:0.0} dB, "
            + $"{report.CharactersEmitted} characters: {text}");

        Assert.True(
            report.HasTone,
            $"{name} contains a real station and no tone was found. "
            + $"The radio was on {capture["Frequency"]} in {capture["Mode"]} with "
            + $"{capture["FilterBandwidth"]} of filter and its pitch set to "
            + $"{capture["CwPitch"]}.");

        // Within a couple of bins of where the capture itself recorded it.
        var recorded = double.Parse(capture["toneHz"]);

        Assert.True(
            Math.Abs(report.ToneHz - recorded) <= 50,
            $"{name} recorded the tone at {recorded:0} Hz and the decoder now "
            + $"answers {report.ToneHz:0} Hz");
    }

    /// <remarks>
    /// <para>Proves HM-DEC-090 against real audio rather than against a
    /// simulation of it. The same recordings once reported ratios near zero on
    /// signals measured at thirty-six decibels and more above the band, because
    /// the figure was averaged across the ninety-five percent of the recording in
    /// which nobody was sending.</para>
    /// </remarks>
    [Theory]
    [MemberData(nameof(Names))]
    public void TheSignalReadsAsStrongAsItIs(string name)
    {
        var report = Decode(name).Decoder.Report;

        Assert.True(
            report.SnrDb >= 15,
            $"{name} holds a plainly audible station and reads {report.SnrDb:0.0} dB");
    }

    /// <remarks>
    /// <para>Proves §0.0 on the air, which is the half of this that matters most.
    /// **These recordings once produced seventeen hundred characters, seventeen
    /// hundred of them marked unsure.** Whatever the decoder can or cannot read
    /// here, it may not fill the screen from the parts it cannot.</para>
    /// <para>The bound is generous on purpose: it is not a claim about how much
    /// of the message is there, only that what comes out is on the scale of Morse
    /// somebody sent in half a minute rather than of noise being sliced.</para>
    /// </remarks>
    [Theory]
    [MemberData(nameof(Names))]
    public void NothingIsInventedFromWhatCannotBeRead(string name)
    {
        var report = Decode(name).Decoder.Report;

        _output.WriteLine(
            $"{name}: {report.ElementsSeen} elements, "
            + $"{report.CharactersEmitted} characters");

        Assert.True(
            report.CharactersEmitted <= 200,
            $"{name} produced {report.CharactersEmitted} characters from half a "
            + "minute, which is more than anybody sent");

        // And a speed, if one is named at all, is one this radio could send.
        if (decoderSpeed(name) is { } wpm)
        {
            Assert.InRange(wpm, CwDecoder.SlowestPlausibleWpm, CwDecoder.FastestPlausibleWpm);
        }

        static int? decoderSpeed(string name) => Decode(name).Decoder.WordsPerMinute;
    }

    /// <remarks>
    /// Proves HM-DEC-090 on the air: the two recordings are two recordings. Three
    /// captures once came back byte-identical with identical analysis, and the
    /// operator reasoned from one recording presented as three. These carry
    /// different fingerprints and different running sample counts, which is the
    /// fix working on real hardware.
    /// </remarks>
    [Fact]
    public void TheCapturesAreGenuinelyDifferentRecordings()
    {
        var all = Directory.GetFiles(Folder, "*.wav").OrderBy(p => p).ToList();

        Assert.True(all.Count >= 2, "there is only one capture to compare");

        var fingerprints = all
            .Select(w => Load(Path.GetFileNameWithoutExtension(w))["fingerprint"])
            .ToList();

        var seen = all
            .Select(w => Load(Path.GetFileNameWithoutExtension(w))["audioSeen"])
            .ToList();

        Assert.Equal(fingerprints.Count, fingerprints.Distinct().Count());
        Assert.Equal(seen.Count, seen.Distinct().Count());
        Assert.All(fingerprints, f => Assert.NotEqual("", f));
    }

    private static string RepositoryRoot()
    {
        var directory = new DirectoryInfo(
            Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location)!);

        while (directory is not null)
        {
            if (Directory.Exists(Path.Combine(directory.FullName, "src", "Hamlet.RadioEngine")))
            {
                return directory.FullName;
            }

            directory = directory.Parent;
        }

        throw new DirectoryNotFoundException("could not find the repository root");
    }
}
