using System.Reflection;
using Hamlet.RadioEngine.Audio;
using Hamlet.RadioEngine.Cw;
using Xunit;
using Xunit.Abstractions;

namespace Hamlet.RadioEngine.Tests.Cw;

/// <summary>One recording made on the air, and what the radio was doing.</summary>
/// <param name="Name">The file, without its extension.</param>
/// <param name="Sidecar">Everything written beside it at the moment of capture.</param>
internal sealed record CapturedSignal(string Name, IReadOnlyDictionary<string, string> Sidecar)
{
    /// <summary>What the capture recorded for one field, or "".</summary>
    public string this[string field]
        => Sidecar.TryGetValue(field, out var value) ? value : "";
}

/// <summary>
/// The decoder against signals that were actually on the air (HM-DEC-091).
/// </summary>
/// <remarks>
/// <para>**THE SEVEN SYNTHETIC FIXTURES ALL PASSED WHILE THE DECODER WAS DEAF ON
/// THE AIR**, and that is the whole argument for these files. Morse generated by
/// the same understanding that built the decoder will confirm that understanding
/// for as long as anybody cares to run it. These two recordings are the first
/// evidence in the project capable of contradicting it.</para>
/// <para>Each carries the rig state at the moment of capture, so a failure here
/// can say what the radio was set to rather than only that something went wrong
/// (§0.0.1).</para>
/// <para>**WHAT THESE TESTS ASSERT IS DELIBERATELY NOT A TRANSCRIPT.** Nobody
/// knows what that station sent; there is no truth to compare against, and
/// inventing one would be worse than having none. What can be asserted is
/// everything that was measured independently and everything §0.0 forbids: the
/// tone is found, it is strong, and nothing is invented from the parts that
/// cannot be read.</para>
/// </remarks>
public sealed class CapturedSignalTests
{
    private readonly ITestOutputHelper _output;

    /// <summary>Creates the tests.</summary>
    /// <param name="output">Where the decode is printed.</param>
    public CapturedSignalTests(ITestOutputHelper output) => _output = output;

    /// <summary>Where the recordings live.</summary>
    public static string Folder { get; } = Path.Combine(
        RepositoryRoot(), "tests", "fixtures", "cw", "captured");

    /// <summary>Every recording, with its sidecar read.</summary>
    public static TheoryData<string> Names
    {
        get
        {
            var data = new TheoryData<string>();

            foreach (var wav in Directory.GetFiles(Folder, "*.wav").OrderBy(p => p))
            {
                data.Add(Path.GetFileNameWithoutExtension(wav));
            }

            return data;
        }
    }

    private static CapturedSignal Load(string name)
    {
        var fields = new Dictionary<string, string>(StringComparer.Ordinal);

        foreach (var line in File.ReadAllLines(Path.Combine(Folder, name + ".txt")))
        {
            var trimmed = line.Trim();
            var space = trimmed.IndexOf(' ');

            if (space > 0)
            {
                fields[trimmed[..space]] = trimmed[(space + 1)..].Trim();
            }
        }

        return new CapturedSignal(name, fields);
    }

    /// <remarks>
    /// Proves HM-DEC-090 on the air: the two recordings are two recordings. Three
    /// captures once came back byte-identical with identical analysis, and the
    /// operator reasoned from one recording presented as three. These carry
    /// different fingerprints and different running sample counts, which is the
    /// fix working on real hardware.
    /// </remarks>
    [Fact]
    public void TheCapturesAreGenuinelyDifferentRecordings()
    {
        var all = Directory.GetFiles(Folder, "*.wav").OrderBy(p => p).ToList();

        Assert.True(all.Count >= 2, "there is only one capture to compare");

        var fingerprints = all
            .Select(w => Load(Path.GetFileNameWithoutExtension(w))["fingerprint"])
            .ToList();

        var seen = all
            .Select(w => Load(Path.GetFileNameWithoutExtension(w))["audioSeen"])
            .ToList();

        Assert.Equal(fingerprints.Count, fingerprints.Distinct().Count());
        Assert.Equal(seen.Count, seen.Distinct().Count());
        Assert.All(fingerprints, f => Assert.NotEqual("", f));
    }

    private static string RepositoryRoot()
    {
        var directory = new DirectoryInfo(
            Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location)!);

        while (directory is not null)
        {
            if (Directory.Exists(Path.Combine(directory.FullName, "src", "Hamlet.RadioEngine")))
            {
                return directory.FullName;
            }

            directory = directory.Parent;
        }

        throw new DirectoryNotFoundException("could not find the repository root");
    }
}
