using System.Reflection;
using Hamlet.RadioEngine.Audio;
using Hamlet.RadioEngine.Training;

namespace Hamlet.RadioEngine.Tests.Cw;

/// <summary>One committed recording, and what is on it.</summary>
/// <param name="Name">File name, without the extension.</param>
/// <param name="Sent">The text that was sent.</param>
/// <param name="WordsPerMinute">The speed it was sent at.</param>
/// <param name="Request">Everything needed to regenerate it exactly.</param>
/// <param name="Clean">
/// True when nothing was done to the signal, so the decode can be asserted
/// character for character.
/// </param>
/// <param name="ReadableShare">
/// The share of the message that has to come back resolved, as a guard against
/// a decoder that passed everything else by going silent. It is per fixture
/// because the impairments are not equally survivable, and pretending they are
/// would mean either excusing a decoder that gave up on noise or demanding it
/// read through something nobody could.
/// </param>
internal sealed record CwFixture(
    string Name,
    string Sent,
    int WordsPerMinute,
    CwSignalRequest Request,
    bool Clean,
    double ReadableShare = 1.0);

/// <summary>
/// The committed CW recordings the decoder is held to.
/// </summary>
/// <remarks>
/// <para>HM-DEC-007 GOVERNS: decoders are built and tested against WAV
/// fixtures, and every decoder bug becomes a replayable case. These are the
/// starting set, covering the speeds a newcomer meets and the four things that
/// actually go wrong on the air.</para>
/// <para>SYNTHESIZED, NOT RECORDED OFF AIR, and that settles a question a
/// public GPL-3.0 repository would otherwise have to answer. An off-air
/// recording carries somebody's callsign and somebody's transmission, which
/// §2.1 makes Tim's to review before it ships. Nothing here belongs to anyone:
/// the audio comes from <see cref="CwSignal"/>, and every file can be
/// regenerated byte for byte from the request beside it, which is what the
/// drift test proves.</para>
/// <para>Eight kilohertz and sixteen-bit mono, which is about a megabyte for
/// the whole set. A CW note lives between three hundred and nine hundred hertz
/// and needs nothing above four kilohertz to be reconstructed exactly, so the
/// forty-eight kilohertz the radio's codec will deliver would be six times the
/// size for nothing at all.</para>
/// </remarks>
internal static class CwFixtures
{
    private const string Call = "CQ DE W1AW K";
    private const string LongCall = "CQ CQ DE W1AW W1AW K";

    /// <summary>Every committed recording.</summary>
    public static IReadOnlyList<CwFixture> All { get; } = new[]
    {
        // The three speeds a newcomer actually meets. Twelve is a patient
        // operator, eighteen is ordinary, twenty-five is a contest.
        new CwFixture(
            "clean-12wpm", Call, 12,
            new CwSignalRequest(Call, WordsPerMinute: 12),
            Clean: true),

        new CwFixture(
            "clean-18wpm", Call, 18,
            new CwSignalRequest(Call, WordsPerMinute: 18),
            Clean: true),

        // **`clean-25wpm` RETIRED 2026-08-17, AND THIS IS ITS REASON**
        // (HM-DEC-103, HM-DEC-107 phase 3). It was the repository's only fast-CW
        // coverage, which is why it was kept through two sessions of failing: a
        // fixture deleted without a replacement is evidence destroyed, and
        // retiring the one that fails while keeping the six that pass would have
        // narrowed what Hamlet is claimed to handle without saying so.
        //
        // It is replaced by `fast-easy`, `fast-working` and `fast-edge` under
        // `tests/fixtures/cw/receiver`, at the same twenty-five words a minute
        // and at three signal-to-noise tiers rather than one. The replacement
        // passes the reference gate at 100 percent, which was the condition set
        // for this retirement and which it only met once the reference's own gap
        // classifier was repaired.
        //
        // What it could never test is what it was made of: tone or exact digital
        // silence between elements, which no receiver produces, so nothing in it
        // exercised the transmit-mute guard, the threshold fit or any refusal
        // (HM-OPEN-018).

        // Prosigns, written in the radio's own notation where "^" keys the
        // characters after it as one symbol (Full Manual p. 19-12).
        new CwFixture(
            "prosigns-18wpm", "W1AW DE K2ABC ^BT R TU ^SK", 18,
            new CwSignalRequest("W1AW DE K2ABC ^BT R TU ^SK", WordsPerMinute: 18),
            Clean: true),

        // A signal down in the noise, which is most of what is on the air.
        new CwFixture(
            "noisy-18wpm", Call, 18,
            new CwSignalRequest(
                Call, WordsPerMinute: 18, Amplitude: 0.3, NoiseAmplitude: 0.17),
            Clean: false,
            ReadableShare: 0.8),

        // Rising and falling, which is what the band does to a distant station.
        new CwFixture(
            "fading-18wpm", LongCall, 18,
            new CwSignalRequest(
                LongCall, WordsPerMinute: 18, NoiseAmplitude: 0.02,
                FadeSeconds: 5, FadeDepth: 0.75),
            Clean: false,
            ReadableShare: 0.6),

        // Somebody else a hundred and fifty hertz away and only three decibels
        // down, keying before the wanted signal even starts. This is the hardest
        // of the set on purpose, and the low bar is the honest one: two stations
        // that close are hard for a person too, and the decoder spends the first
        // half of the message with its speed estimate poisoned by somebody
        // else's keying. What it must do is say so, which is why the confident
        // mistakes test still applies here in full.
        new CwFixture(
            "interference-18wpm", Call, 18,
            new CwSignalRequest(
                Call, WordsPerMinute: 18, NoiseAmplitude: 0.04,
                InterferenceHz: 450, InterferenceAmplitude: 0.35,
                InterferenceWpm: 24),
            Clean: false,
            ReadableShare: 0.25),
    };

    /// <summary>Where the recordings live.</summary>
    public static string Folder { get; } = Path.Combine(
        RepositoryRoot(), "tests", "fixtures", "cw");

    /// <summary>The path of one recording.</summary>
    /// <param name="fixture">The fixture.</param>
    /// <returns>Its full path.</returns>
    public static string PathOf(CwFixture fixture)
        => Path.Combine(Folder, fixture.Name + ".wav");

    /// <summary>Read a recording from disk.</summary>
    /// <param name="fixture">The fixture.</param>
    /// <returns>Its audio.</returns>
    public static MonoAudio Read(CwFixture fixture) => WavAudio.Read(PathOf(fixture));

    /// <summary>
    /// Write every recording, replacing what is there.
    /// </summary>
    /// <param name="folder">Destination folder.</param>
    /// <remarks>
    /// Regenerating on purpose is a deliberate act with a ruling behind it. The
    /// drift test exists so that regenerating by accident cannot happen quietly,
    /// since a fixture that changed would take its own assertions with it.
    /// </remarks>
    public static void WriteAll(string folder)
    {
        Directory.CreateDirectory(folder);

        foreach (var fixture in All)
        {
            WavAudio.Write(
                Path.Combine(folder, fixture.Name + ".wav"),
                CwSignal.Generate(fixture.Request));
        }
    }

    /// <summary>The repository root, found by walking up from the test binary.</summary>
    private static string RepositoryRoot()
    {
        var directory = new DirectoryInfo(
            Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location)!);

        while (directory is not null)
        {
            if (Directory.Exists(Path.Combine(directory.FullName, "src", "Hamlet.RadioEngine")))
            {
                return directory.FullName;
            }

            directory = directory.Parent;
        }

        throw new DirectoryNotFoundException("could not find the repository root");
    }
}
