using Hamlet.App.ViewModels;
using Hamlet.RadioEngine.Audio;
using Hamlet.RadioEngine.Cw;
using Xunit;
using Xunit.Abstractions;

namespace Hamlet.App.Tests.Cw;

/// <summary>
/// Work instruction 411 task 3: the sidecar's three signal lines regenerated from
/// a saved capture through the writer's own code, so the change reads as text.
/// </summary>
/// <remarks>
/// <para>**NO CAPTURE IN THE TREE IS EDITED.** The regenerated lines go to
/// `.run-unit/unit411-sidecar-&lt;stamp&gt;.txt`, beside the unit's other
/// evidence.</para>
/// <para>**WHAT IS REGENERATED AND WHAT IS NOT.** The three lines come from
/// <c>TonePeakRecordLine</c>, <c>KeyingRecordLine</c> and
/// <c>ElementHzRecordLine</c>, which the sheet writer calls for exactly these
/// lines. The rest of the sheet is composed inside the view model from a live
/// session and is not rebuilt here. The decoder and the meter are fresh and hear
/// only this file, so the running totals are this file's rather than an
/// evening's.</para>
/// </remarks>
public sealed class TheSidecarIsReReadTests
{
    private readonly ITestOutputHelper _output;

    /// <summary>Creates the tests.</summary>
    /// <param name="output">Where the lines are printed.</param>
    public TheSidecarIsReReadTests(ITestOutputHelper output) => _output = output;

    /// <summary>Regenerate and write the three lines for one saved capture.</summary>
    [Theory]
    [InlineData("cw-2026-09-23-173723")]
    [InlineData("cw-2026-08-22-014113")]
    public void TheThreeLinesAreWrittenAgainFromTheSavedAudio(string stamp)
    {
        var root = Root();
        var audio = WavAudio.Read(Path.Combine(
            root, "tests", "fixtures", "cw", "captured", "unadjudicated", stamp + ".wav"));

        var decoder = new CwDecoder(audio.SampleRate);

        using (var source = new BufferedAudioSource(audio))
        {
            decoder.Listen(source);
            source.PumpAll();
            decoder.Flush();
        }

        var report = decoder.Report;

        var meter = new CwKeyingMeter();
        var window = (int)(CwKeyingThresholds.Window.TotalSeconds * audio.SampleRate);

        for (var end = window; end <= audio.Samples.Length; end += audio.SampleRate)
        {
            meter.Update(new MonoAudio(audio.SampleRate, audio.Samples[(end - window)..end]));
        }

        var lines = new[]
        {
            $"# {stamp}.wav, regenerated by work instruction 417 task 2; a fresh decoder "
            + "and a fresh meter, this file only",
            MainWindowViewModel.TonePeakRecordLine(audio, report),
            $"elements   {report.ElementsSeen} seen, {report.ElementsResolved} resolved"
            + "  (this file only, a fresh decoder)",
            MainWindowViewModel.KeyingRecordLine(meter.Reading),
            MainWindowViewModel.ElementHzRecordLine(audio, report),
        };

        var written = Path.Combine(root, ".run-unit", $"unit417-sidecar-{stamp}.txt");
        File.WriteAllLines(written, lines);

        foreach (var line in lines)
        {
            _output.WriteLine(line);
        }

        Assert.True(File.Exists(written));
        Assert.StartsWith("tonePeak   ", lines[1], StringComparison.Ordinal);
        Assert.StartsWith("keying     ", lines[3], StringComparison.Ordinal);
        Assert.StartsWith("elementHz  ", lines[4], StringComparison.Ordinal);
    }

    private static string Root()
    {
        var here = new DirectoryInfo(AppContext.BaseDirectory);

        while (here is not null
               && !Directory.Exists(Path.Combine(here.FullName, "tests", "fixtures")))
        {
            here = here.Parent;
        }

        Assert.NotNull(here);

        return here!.FullName;
    }
}
