{
  if ($0 ~ /^    private readonly int _keyingHops;$/) { print; print "    private readonly int _holdHops;"; next }
  if ($0 ~ /^    private CwEnvelopeReading _reading = CwEnvelopeReading.None;$/) {
    print
    print ""
    print "    // The station being held (work instruction 485): its bin, the last hop a mark arrived there,"
    print "    // and its bars' level; -1 where nothing is held."
    print "    private int _holdBin = -1;"
    print "    private long _holdLastMarkHop;"
    print "    private double _holdBarDb = double.NaN;"
    next
  }
  if ($0 ~ /^        _keyingHops = \(int\)Math.Round\(KeyingSeconds \* 1000 \/ HopMs\);$/) { print; print "        _holdHops = (int)Math.Round(HoldSeconds * 1000 / HopMs);"; next }
  if ($0 ~ /^        var watched = _bins\[_watched\];$/ && !done) {
    print "        // **THE STATION IS HELD THROUGH ITS GAPS** (work instruction 485, R97). Once bars are found"
    print "        // at a pitch, keying stays true there while marks keep arriving - a paired bar, or a run"
    print "        // at least a bar long standing within the flat tolerance of the station's bars - and is let"
    print "        // go only when none has arrived for HoldSeconds. While held, the watched pitch stays on the"
    print "        // station, unless the radio points elsewhere."
    print "        if (_holdBin >= 0 && pointed >= 0)"
    print "        {"
    print "            _holdBin = pointed;"
    print "        }"
    print ""
    print "        if (_holdBin >= 0)"
    print "        {"
    print "            var held = _bins[_holdBin];"
    print "            var heldEval = evals[_holdBin];"
    print "            var lastBar = heldEval.Marked.Count > 0 ? heldEval.Marked.Max(m => m.End) : -1;"
    print "            var run = held.Open;"
    print ""
    print "            if (!double.IsNaN(heldEval.BarDb))"
    print "            {"
    print "                _holdBarDb = heldEval.BarDb;"
    print "            }"
    print ""
    print "            if (lastBar > _holdLastMarkHop)"
    print "            {"
    print "                _holdLastMarkHop = lastBar;"
    print "            }"
    print ""
    print "            if (run is not null && run.End == hop && run.Count >= _minBarHops"
    print "                && !double.IsNaN(_holdBarDb) && run.Mean >= _holdBarDb - FlatToleranceDb)"
    print "            {"
    print "                _holdLastMarkHop = hop;"
    print "            }"
    print ""
    print "            if (hop - _holdLastMarkHop > _holdHops)"
    print "            {"
    print "                _holdBin = -1;"
    print "                _holdBarDb = double.NaN;"
    print "            }"
    print "        }"
    print ""
    print "        if (_holdBin < 0 && keying)"
    print "        {"
    print "            _holdBin = _watched;"
    print "            _holdLastMarkHop = hop;"
    print "            _holdBarDb = evals[_watched].BarDb;"
    print "        }"
    print ""
    print "        if (_holdBin >= 0)"
    print "        {"
    print "            keying = true;"
    print ""
    print "            if (pointed < 0)"
    print "            {"
    print "                _watched = _holdBin;"
    print "            }"
    print "        }"
    print ""
    print
    done = 1
    next
  }
  print
}
