@echo off
rem ============================================================
rem  unit296-append.bat  -  unit 296's one call to
rem                         outcome-append.bat
rem
rem  IT WAS NOT RUN AND IT WAS NOT ATTEMPTED. Work instruction
rem  296 records that units 289, 290, 291 and 292 each measured
rem  the same refusal - the sandbox answering "This command
rem  requires approval" to every .bat under tools/arbiter, in a
rem  non interactive session with nobody to approve it - that
rem  units 293, 294 and 295 were told a further measurement was
rem  worth nothing and did not attempt one, and that the
rem  authoring environment and the executing one differ, the
rem  executing one being the refused one. This session did not
rem  spend a call on it.
rem
rem  It met the same class of refusal independently four times on
rem  ordinary work: sed -i on Directory.Build.props, a heredoc
rem  redirected to /tmp, a python rewrite of PROJECT_STATUS.md,
rem  and git stash push. Each was worked around with the file
rem  editing tools. That is a fourth session refused and not a
rem  fourth measurement of these scripts.
rem
rem  The entry was written with the file editing tools instead, in
rem  the format outcome-entry.py produces, and says so on its own
rem  face. This file is committed so the arguments can be replayed
rem  rather than reconstructed from the entry.
rem
rem  NO APOSTROPHES BELOW. Twenty two units of measured shell
rem  behaviour: this shell will not carry a quoted heredoc
rem  containing one, and an apostrophe inside an argument to the
rem  arbiter scripts aborted their inner PowerShell mid run while
rem  the script still exited 0.
rem ============================================================

setlocal

call "%~dp0outcome-append.bat" ^
  296 ^
  1 ^
  "done" ^
  "Measured FT4s decode rate at HEAD on a lattice no analysis grid can flatter - twenty five placements spanning one whole FT4 tone spacing and one whole FT4 symbol period, five divisions a side so that no power of two oversampling can turn an off grid cell into an on grid one, asserted before anything was measured - and quoted the deficit in decibels against an on grid ladder re drawn a decibel at a time. Then swept the analysis grids the arithmetic allows, since Ft4WaterfallGeometry already takes both oversamplings and Ft4SlotDecoder already takes a geometry, so a denser grid costs zero lines of source to try. Then adopted the one grid that closed the gap inside the slot budget with zero wrong decodes, in one file, with the whole measurement written into it. Then re took step 1s must pass criteria at placements drawn rather than chosen, kept the on grid runs beside them, and re drew the sensitivity ladder placement averaged." ^
  "The deficit the tree had guessed at two to three decibels is a measurement: at -13 dB, where the on grid rate is exactly one, HEAD kept 808 of 900 placement averaged and 19 of 36 at its worst cell, which interpolates to 2.4 dB at the worst placement and 1.3 dB averaged. But the grid sweep answered a question nobody had asked and it decided the night. FREQUENCY OVERSAMPLING ABOVE 2 DESTROYS THE DECODE AND DESTROYS THE ON GRID ONE FIRST - 2x4 and 4x4 both fall from 36 of 36 to 0 of 36 at -13 dB - because Ft8Monitors analysis frame is BlockSize times FrequencyOversampling samples long, so at 4 it spans four FT4 symbol periods and a 4-FSK tone that changes every symbol is smeared across the window. Time oversampling costs nothing of the kind: it only samples the same length frame more often, and sub symbol alignment is the axis the off grid loss actually lives on. At 4x2 the placement average at -13 dB is 894 of 900 and the worst cell 34 of 36, the on grid cell does not move, one slot costs 151 ms against a 7.5 s slot, and the wrong count is 0 in 10800 slots across the whole sweep. The second surprise was the cost of that: Ft4DeepSignalToNoise.Ft4CandidateTimeBiasSeconds is minus one symbol period and was right at two analyses per symbol; at four the measured bias is one further sub block, so the estimators window opens 12 ms late against a 12 ms alignment search and works at its own limit with no margin. Ft4Unit294SnrAgreementTests is red for exactly that reason and is left red on purpose." ^
  "continue" ^
  "Step 1s must pass criteria were measured entirely at 1000.0 Hz with Ft4Waveform.SynthesizeSlots fixed padding - 96 bins exactly and a whole number of time steps - which is a placement on Hamlets own analysis grid, and the decoders own test file recorded 106 of 106 on grid against 17 of 106 at the cell centre. Step 5 is Tim tuning to an FT4 frequency at the radio, where nothing on 14.080 arranges itself to Hamlets convenience and no unit can repair anything. Four units in a row had aimed at step 4, which has every criterion answered twice over; this was the last bench shaped night that could decide whether he sees a table or an empty screen." ^
  "Four things on my own authority. First, I added a 4x2 cell to the grid sweep, which the instructions list does not contain, because 2x4 collapsed and a sweep that only ever moved both axes together could not say which one did it - and it turned out to be the whole answer. Second, I did not run 4x8, which the instruction lists as conditional on the clock: it carries frequency oversampling 8, the axis two separate grids had already shown to be destructive for a reason read out of Ft8Monitors source, and it cost ten minutes to confirm a third collapse. That is a sizing decision and it is reported as one. Third, I left Ft4Unit294SnrAgreementTests RED rather than weakening its assertion to green. It asserts the measured candidate time bias equals the shipped constant, which was a true statement about one geometry and is a false one about the shipping geometry; the correction is one line in src/Ft8Sharp.Deep, which this instruction forbids this unit to touch, so the discrepancy is measured, guarded by a new test that is green at zero margin and red the moment it worsens, and named for a ruling. Fourth, I updated the snr tooltip and ReadFt4s remarks from 0.58/1.41 over 970 to 0.56/1.39 over 1048, which task 6 licenses, because a stale figure on a live tooltip is the fault this project keeps a card against. I did NOT settle the 4.48 against 5.04 figure, the widened candidate sweep, the version scheme, the estimators strong signal bias or the four inherited reds, and I put no length of any kind on a screen." ^
  "PHASE_PLAN.md step 1, whose first and third must pass criteria are the hundred message round trip and the zero wrong count and whose fourth is the sensitivity ladder, together with Tims ruling of 2026-09-08 that anything FT8 does that FT4 does not is a gap rather than a scope decision a unit may make - and FT8 does not lose its decodes off grid, 278 of 306 at the cell centre against 283 on grid, because Ft8Sharp.Deeps fine sync recovers them. The faithfulness ruling is honoured on exactly the terms unit 289 recorded for Ft4SyncSearch.DefaultLastBlockOffset: time_osr and freq_osr are parameters of monitor_init and 2 and 2 are demo/decode_ft8.cs file scope judgement about how much work to do, the same class of number as kMin_score and kMax_candidates, and nothing about the modulation, the tables, the codeword, the sync patterns or the waveform changes. Also PHASE_PLAN.mds named alternatives table - the tree disagrees with this plan, the tree wins, report the mismatch and continue." ^
  "one session, eight of eight tasks, none dropped including the named drop candidate, no unfiltered test suite run, every test filtered by exact name or exact class name and foregrounded, every dotnet build foregrounded, one measured revert and rebuild to establish that an inherited red was inherited, about forty minutes of foreground measurement across four grid sweeps and a ladder, and one self inflicted break of Directory.Build.props - two hyphens inside an XML comment - caught on the next build and pushed as its own fix." ^
  "Hamlet reads FT4 signals that arrived where real signals arrive rather than only the ones it placed on its own analysis grid. At -13 dB, where the on grid rate is exactly one, a station drawn at random within one tone spacing and one symbol period now decodes 105 times in 106 where it decoded 95, and averaged over a lattice of twenty five placements 894 of 900 where it was 808. How much the old grid was costing is a measured number - 2.4 dB at the worst placement - rather than a guess in a remark, and the reason the fix is on the time axis and not the frequency one is read out of the ports own analysis frame rather than guessed at. FT8s grid does not move by any route and that is asserted, extent by extent, alongside the assertion that a caller asking for upstreams own 2 and 2 still gets upstreams own result." ^
  "" ^
  "executed" ^
  "All four exit criteria are met and criteria 1 and 3 are now met AT A PLACEMENT HAMLET DID NOT CHOOSE, which is what they had never been. CRITERION 1: 106 messages from Ft4RoundTripCorpus - compound callsigns, grids, reports and RR73 - each at a frequency drawn uniform in one whole tone spacing and a lead drawn uniform in one whole symbol period from seed 296, decoding 106 of 106 at the shipping grid and 106 of 106 at upstreams, 0 missed at both; at -13 dB on the same draws it is 105 of 106 against upstreams 95 of 106. Ft4RoundTripTestss on grid assertion was not edited and still reads 106 of 106 at the new grid, so the two figures stand side by side. CRITERION 2 is unit 289s, judged as measured from the audio with the 4.48 against 5.04 disagreement named with both numbers, and was NOT re measured tonight; it is carried, not restated as this units. CRITERION 3: zero wrong decodes, counted separately from missed at every cell and every rung throughout - 0 in the 2988 slots of the HEAD trace, 0 in each of the four grid sweeps and 0 in 10800 slots across them, 0 in both round trips at both grids, and 0 in the ladders 3200 slots. CRITERION 4, nice to pass and the named drop candidate, was NOT dropped: all eight rungs drawn placement averaged over the lattice beside the on grid column, 400 trials a rung on a stated sixteen message subset, 400 of 400 down to -10 dB, 396 of 400 at -13, 188 of 400 at -15, 2 of 400 at -17, nothing below, 0 wrong. THE CONTROLS: a git diff stat against a5b9628 shows three files under src and no more - Ft4WaterfallGeometry.cs, Ft8Reception.cs and src/Ft8Sharp/Directory.Build.props - nothing under src/Ft8Sharp.Deep and no FT8 decode path file; FT8s own defaults are asserted at 2 and 2 on the constants and on a built geometry; the FT8 whole chain control is 3 of 3 with two of them an inherited red cleared, proved by reverting; and one FT4 slot driven through Ft8Reader.Read with DigitalMode.Ft4 at a placement a third of a bin and a third of a sub block off grid came back as itself in 84 ms a slot, with both slots stamped Ft8Sharp and never Ft8Sharp.Deep. ONE ITEM WANTS A RULING AND IT IS NOT IN THE WAY OF A STEP 1 CRITERION: Ft4DeepSignalToNoise.Ft4CandidateTimeBiasSeconds is stale by one sub block at the new grid and its alignment search absorbs the error at exactly its own limit, so the estimator still measures 0.56 dB mean absolute error over 1048 messages, better than the 0.58 it read before, and Ft4Unit294SnrAgreementTests is left red naming it."

endlocal & exit /b %ERRORLEVEL%
